version: '3.6'
services:

  nginx:
    image:  nginx:1.14 
    # build:
      # context: ./nginx
      # dockerfile: Dockerfile
    volumes:
        - .:/usr/share/nginx/html
        # - ./docker.nginx.conf:/etc/nginx/nginx.conf
        - ./docker.nginx.default.conf:/etc/nginx/conf.d/default.conf
    ports:
        -   "3008:80"
