version: '3.6'
services:

  vue425b:
    image:  nginx:1.14 
    # build:
      # context: ./nginx
      # dockerfile: Dockerfile
    volumes:
        - .:/usr/share/nginx/html
    ports:
        -   "3001:80"
